-- Transactional integration test. Fixtures and queued mail are rolled back.
begin;
do $$
declare employee uuid:=gen_random_uuid(); admin uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); company text:='review-test-'||gen_random_uuid(); other_company text:='review-test-other-'||gen_random_uuid(); aid uuid; n bigint;
begin
 insert into auth.users(id,email,email_confirmed_at) values(employee,employee||'@example.invalid',now()),(admin,admin||'@example.invalid',now()),(outsider,outsider||'@example.invalid',now());
 insert into public.phishaware_team(id,state) values(company,'{"organization":"Review test","employees":[],"events":[]}'),(other_company,'{"organization":"Other test","employees":[],"events":[]}');
 insert into public.phishaware_access(email,role,status,company_id,employee_id) values(employee||'@example.invalid','Employee','approved',company,'test-employee'),(admin||'@example.invalid','Administrator','approved',company,null),(outsider||'@example.invalid','Administrator','approved',other_company,null);
 insert into public.phishaware_mailboxes(user_id,company_id,email,token_cipher) values(employee,company,employee||'@example.invalid','test-only-not-a-token');
 execute 'set local role service_role';
 perform public.phishaware_store_finding(employee,company,'{"message_id":"safe-test","subject":"Test request","sender":"sender@example.invalid","received_at":"2026-10-03T20:00:00Z","risk":"Medium","reasons":["Test warning"],"recommendation":"Verify sender"}');
 if not public.phishaware_review_finding(employee,company,'safe-test','reviewed') then raise exception 'Request failed';end if;
 select id into aid from public.phishaware_email_alerts where user_id=employee and message_id='safe-test' and request_kind='review' and status='open';
 if aid is null then raise exception 'Admin request missing';end if;
 if public.phishaware_complete_email_review(employee,employee||'@example.invalid',company,aid,'safe','') then raise exception 'Employee granted review authority';end if;
 if public.phishaware_complete_email_review(outsider,outsider||'@example.invalid',company,aid,'safe','') then raise exception 'Cross-company access granted';end if;
 if not public.phishaware_complete_email_review(admin,admin||'@example.invalid',company,aid,'safe','Sender verified through a known contact') then raise exception 'Admin decision failed';end if;
 if not exists(select 1 from public.phishaware_notification_history where user_id=employee and message_id='safe-test' and review_outcome='safe' and not notification_read and risk='Medium') then raise exception 'Employee decision notification missing or risk changed';end if;
 if not exists(select 1 from public.phishaware_notification_history where user_id=employee and message_id='safe-test' and review_note like '%Original scan: Medium risk.%' and review_note like '%Test warning%' and review_note like '%Administrator details: Sender verified through a known contact%') then raise exception 'Automatic summary or administrator details missing';end if;
 if not exists(select 1 from public.phishaware_audit where company_id=company and actor=admin||'@example.invalid' and category='Email review') then raise exception 'Review audit missing';end if;
 n:=public.phishaware_notification_count(employee,company);if n<>1 then raise exception 'Unread count wrong: %',n;end if;
 if public.phishaware_complete_email_review(admin,admin||'@example.invalid',company,aid,'safe','Duplicate') then raise exception 'Duplicate completion accepted';end if;
 perform public.phishaware_review_finding(employee,company,'safe-test','reviewed');
 if not exists(select 1 from public.phishaware_email_alerts where id=aid and status='resolved') then raise exception 'Duplicate request reopened decision';end if;
 perform public.phishaware_read_notifications(employee,company,false,'safe-test');
 if public.phishaware_notification_count(employee,company)<>0 then raise exception 'Read count did not reset';end if;
 if not exists(select 1 from public.phishaware_search_notifications(employee,company,true,'',0) where review_outcome='safe') then raise exception 'Read decision lost from history';end if;
 perform public.phishaware_store_finding(employee,company,'{"message_id":"blank-note-test","subject":"Reported invoice","sender":"sender@example.invalid","received_at":"2026-10-03T20:00:00Z","risk":"Medium","reasons":["Reply address mismatch"],"recommendation":"Verify sender"}');
 perform public.phishaware_review_finding(employee,company,'blank-note-test','reported');
 select id into aid from public.phishaware_email_alerts where user_id=employee and message_id='blank-note-test';
 if not public.phishaware_complete_email_review(admin,admin||'@example.invalid',company,aid,'safe','') then raise exception 'One-click safe review failed';end if;
 if not exists(select 1 from public.phishaware_notification_history where user_id=employee and message_id='blank-note-test' and not notification_read and review_outcome='safe' and review_note like '%Reported invoice%' and review_note like '%Original scan: Medium risk.%' and review_note like '%Reply address mismatch%' and review_note like '%marked safe%' and length(review_note)<=1000) then raise exception 'Automatic employee review summary missing';end if;
 if not exists(select 1 from public.phishaware_email_alerts where id=aid and status='resolved' and review_note like '%Reported invoice%') then raise exception 'Admin summary missing';end if;
 if not exists(select 1 from public.phishaware_email_findings where user_id=employee and message_id='blank-note-test' and risk='Medium' and review_note like '%Reply address mismatch%') then raise exception 'Finding summary missing or scan rating changed';end if;
 if public.phishaware_notification_count(employee,company)<>1 then raise exception 'Automatic review did not create unread notification';end if;
 perform public.phishaware_store_finding(employee,company,'{"message_id":"action-test","subject":"High risk test","sender":"sender@example.invalid","received_at":"2026-10-03T20:00:00Z","risk":"High","reasons":["Test warning"],"recommendation":"Do not open"}');
 perform public.phishaware_review_finding(employee,company,'action-test','reported');
 select id into aid from public.phishaware_email_alerts where user_id=employee and message_id='action-test';
 if public.phishaware_complete_email_review(admin,admin||'@example.invalid',company,aid,'action_taken','') then raise exception 'Empty action accepted';end if;
 if not public.phishaware_complete_email_review(admin,admin||'@example.invalid',company,aid,'action_taken','Reported sender. Do not interact with the message.') then raise exception 'Action completion failed';end if;
 if not exists(select 1 from public.phishaware_notification_history where user_id=employee and message_id='action-test' and review_outcome='action_taken' and not notification_read and risk='High') then raise exception 'Action notification missing';end if;
 if has_function_privilege('authenticated','public.phishaware_complete_email_review(uuid,text,text,uuid,text,text)','execute') or has_function_privilege('anon','public.phishaware_complete_email_review(uuid,text,text,uuid,text,text)','execute') then raise exception 'Review RPC exposed to clients';end if;
 raise notice 'PASS: review requests, tenant isolation, safe/action outcomes, unread/history, duplicate protection, audit, private RPC';
end;$$;
rollback;
