import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=readFileSync('supabase/functions/phishaware/index.ts','utf8');
const library=ts.transpileModule(readFileSync('lib/platform.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const exports={};vm.runInNewContext(library,{exports,crypto:globalThis.crypto,Date,Math});
const state=exports.emptyWorkspace();state.employees=[{id:'one',email:'employee@example.invalid',name:'One',active:true},{id:'two',email:'other@example.invalid',name:'Two',active:true}];state.campaigns=[{id:'own',status:'Active',name:'Own'},{id:'other',status:'Active',name:'Other'}];state.deliveries=[{id:'d1',employeeId:'one',campaignId:'own',opened:false},{id:'d2',employeeId:'two',campaignId:'other',opened:false}];
function handler(role='Employee',status='sent',company='main'){
 let fn;const db={rpc:async()=>({data:true}),auth:{getUser:async()=>({data:{user:{id:'user',email:'employee@example.invalid',email_confirmed_at:'confirmed'}}})},from:table=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:table==='phishaware_access'?{role,status,employee_id:'one',company_id:company}:null}),single:async()=>({data:{state,revision:1}})};return q;}};
 const cleaned=source.replace(/^import .*\n/gm,'').replace('const db=createClient', 'const db=createClient');
 const compiled=ts.transpileModule(cleaned,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
 vm.runInNewContext(compiled,{...exports,readBounded:async(req,max)=>{const text=await req.text();if(text.length>max)throw Error('Request too large');return text;},mailReady:()=>false,flushMail:async()=>({configured:false,sent:0,failed:0}),createClient:()=>db,Deno:{env:{get:()=>''},serve:f=>fn=f},Response,Request,Set,Date,JSON,structuredClone});return fn;
}
const request=body=>new Request('https://edge.example.invalid',{method:'POST',headers:{Authorization:'Bearer test'},body:JSON.stringify(body)});
test('uninvited accounts are denied',async()=>{const r=await handler('Employee','failed')(request({action:'load'}));assert.equal(r.status,403);});
test('employee sees only assigned records',async()=>{const r=await handler()(request({action:'load'}));assert.equal(r.status,200);const data=await r.json();assert.deepEqual(data.workspace.employees.map(e=>e.id),['one']);assert.deepEqual(data.workspace.deliveries.map(e=>e.id),['d1']);assert.deepEqual(data.workspace.campaigns.map(e=>e.id),['own']);});
test('employee cannot save administrator state',async()=>{assert.equal((await handler()(request({action:'save'}))).status,403);});
test('employee cannot send invitations',async()=>{assert.equal((await handler()(request({action:'invite',employeeIds:['two']}))).status,403);});
test('employee cannot respond to another employee delivery',async()=>{const r=await handler()(request({action:'employee',kind:'response',deliveryId:'d2',response:'clicked'}));assert.equal(r.status,400);});
test('missing user token is denied',async()=>{const r=await handler()(new Request('https://edge.example.invalid',{method:'POST',body:'{}'}));assert.equal(r.status,401);});

test('employee cannot select another company',async()=>{assert.equal((await handler()(request({action:'load',companyId:'another'}))).status,403);});
test('company administrator cannot select another company',async()=>{assert.equal((await handler('Administrator')(request({action:'load',companyId:'another'}))).status,403);});
test('company administrator cannot create another company',async()=>{assert.equal((await handler('Administrator')(request({action:'create-company'}))).status,403);});
test('employees cannot request company analytics',async()=>assert.equal((await handler()(request({action:'admin-metrics',start:'2026-10-01',end:'2026-11-01'}))).status,403));
test('employees cannot request audit records',async()=>assert.equal((await handler()(request({action:'audit'}))).status,403));
test('analytics access cannot cross company boundaries',async()=>assert.equal((await handler('Administrator')(request({action:'admin-metrics',companyId:'other'}))).status,403));
test('audit access cannot cross company boundaries',async()=>assert.equal((await handler('Administrator')(request({action:'audit',companyId:'other'}))).status,403));
test('analytics rejects reversed date range',async()=>assert.equal((await handler('Administrator')(request({action:'admin-metrics',start:'2026-11-01',end:'2026-10-01'}))).status,400));
test('audit rejects negative pages',async()=>assert.equal((await handler('Administrator')(request({action:'audit',page:-1}))).status,400));
function adminHarness(){let fn;const records=[],queries=[];const db={rpc:async()=>({data:true}),auth:{getUser:async()=>({data:{user:{id:'verified-admin',email:'admin@example.invalid',email_confirmed_at:'yes'}}})},from:table=>{const filters={};const q={select:()=>q,eq:(k,v)=>{filters[k]=v;queries.push([table,k,v]);return q;},gte:(k,v)=>{queries.push([table,k,v]);return q;},lt:(k,v)=>{queries.push([table,k,v]);return q;},order:()=>q,limit:()=>q,range:(a,b)=>{queries.push([table,'range',a,b]);return q;},insert:async data=>{records.push([table,data]);return {error:null};},single:async()=>({data:{state,revision:1}}),maybeSingle:async()=>({data:table==='phishaware_access'&&filters.email==='admin@example.invalid'?{role:'Administrator',platform_admin:true,status:'sent',company_id:'main'}:null}),then:resolve=>resolve({data:[],error:null})};return q;}};const cleaned=source.replace(/^import .*\n/gm,'');vm.runInNewContext(ts.transpileModule(cleaned,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{...exports,readBounded:req=>req.text(),mailReady:()=>false,flushMail:async()=>({configured:false,sent:0,failed:0}),createClient:()=>db,Deno:{env:{get:()=>''},serve:f=>fn=f},crypto:globalThis.crypto,Response,Request,Set,Date,JSON,structuredClone});return {fn,records,queries};}
test('company onboarding saves named employee without granting administrator access',async()=>{const h=adminHarness(),r=await h.fn(request({action:'create-company',name:'Example organization',personName:'Invited Person',adminEmail:'person@example.invalid'}));assert.equal(r.status,200);const company=h.records.find(r=>r[0]==='phishaware_team')[1];assert.equal(company.state.employees[0].name,'Invited Person');assert.equal(company.state.employees[0].email,'person@example.invalid');assert.equal(company.audit_actor,'admin@example.invalid');assert.ok(!h.records.some(r=>r[0]==='phishaware_access'));});
test('onboarding rejects empty individual name',async()=>{const h=adminHarness();assert.equal((await h.fn(request({action:'create-company',name:'Example',personName:'',adminEmail:'person@example.invalid'}))).status,400);assert.equal(h.records.length,0);});
test('admin metrics query uses authorized company and exclusive date boundaries',async()=>{const h=adminHarness();assert.equal((await h.fn(request({action:'admin-metrics',start:'2026-10-01',end:'2026-11-01'}))).status,200);assert.ok(h.queries.some(q=>q[0]==='phishaware_daily_metrics'&&q[1]==='company_id'&&q[2]==='main'));assert.ok(h.queries.some(q=>q[1]==='day'&&q[2]==='2026-11-01'));});
test('audit reads are company scoped and paginated',async()=>{const h=adminHarness();assert.equal((await h.fn(request({action:'audit',page:2}))).status,200);assert.ok(h.queries.some(q=>q[0]==='phishaware_audit'&&q[1]==='company_id'&&q[2]==='main'));assert.ok(h.queries.some(q=>q[1]==='range'&&q[2]===200&&q[3]===300));});

test('employee cannot acknowledge or reply to administrator support requests',async()=>{for(const action of ['support-read','support-reply'])assert.equal((await handler()(request({action,id:'00000000-0000-0000-0000-000000000000',reply:'Test reply'}))).status,403);});
test('support submission rejects invalid target and oversize messages',async()=>{for(const extra of [{target:'other'},{message:'x'.repeat(4001)}])assert.equal((await handler()(request({action:'support-submit',category:'Complaint',target:'company',subject:'Example',message:'Example complaint',...extra}))).status,400);});
test('support requests cannot select another company',async()=>{assert.equal((await handler()(request({action:'support-submit',companyId:'another',category:'Feedback',target:'company',subject:'Example',message:'Example feedback'}))).status,403);});
