import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {createRequire} from 'node:module';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const exports={};const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
vm.runInNewContext(compile(readFileSync('lib/platform.ts','utf8')),{exports,crypto:globalThis.crypto,Date,Math,Set});
test('five-question knowledge checks pass at four correct answers',()=>{for(const m of exports.modules){const answers=m.questions.map(q=>q.answer);answers[0]=(answers[0]+1)%m.questions[0].options.length;assert.equal(exports.gradeTraining(m.id,answers),80);answers[1]=(answers[1]+1)%m.questions[1].options.length;assert.equal(exports.gradeTraining(m.id,answers),60);}});
test('grading rejects invalid answer indices, fractional answers, omissions, and unknown modules',()=>{const m=exports.modules[0];for(const answers of [[-1,0,0,0,0],[9,0,0,0,0],[0.5,0,0,0,0],[0,0],null])assert.throws(()=>exports.gradeTraining(m.id,answers));assert.throws(()=>exports.gradeTraining('unknown',[0,0,0,0,0]));});
test('completion rate excludes obsolete modules and duplicate completion records',()=>{const w=exports.emptyWorkspace();w.employees=[{id:'one',active:true}];w.completions=[{employeeId:'one',moduleId:'senders',score:100},{employeeId:'one',moduleId:'senders',score:100},{employeeId:'one',moduleId:'unknown',score:100}];assert.equal(exports.completionRate(w,'one'),13);});
test('downloaded lesson notes include practical guidance without quiz answer keys',()=>{for(const m of exports.modules){const text=exports.trainingNotes(m);assert.ok(text.includes(m.scenario.action));assert.ok(text.includes(m.checklist[0]));assert.ok(text.includes(m.resources[0].url));assert.ok(!text.includes(m.questions[0].prompt));}});
function harness(){let handler;let state=exports.emptyWorkspace();state.employees=[{id:'own',name:'Employee',email:'employee@example.invalid',active:true}];const writes=[];const db={auth:{getUser:async()=>({data:{user:{id:'verified-user',email:'employee@example.invalid',email_confirmed_at:'yes'}}})},rpc:async()=>({data:true}),from:table=>{let update;const q={select:()=>q,eq:()=>q,single:async()=>({data:{state,revision:1}}),update:values=>{update=values;return q;},maybeSingle:async()=>{if(table==='phishaware_access')return {data:{role:'Employee',status:'sent',company_id:'main',employee_id:'own'}};if(update){writes.push(update);state=update.state;return {data:{revision:update.revision}};}return {data:null};}};return q;}};vm.runInNewContext(compile(readFileSync('supabase/functions/phishaware/index.ts','utf8').replace(/^import .*\n/gm,'')),{...exports,readBounded:r=>r.text(),mailReady:()=>false,flushMail:async()=>({configured:false}),createClient:()=>db,Response,Request,Date,Set,JSON,structuredClone,Deno:{env:{get:()=>''},serve:f=>handler=f}});return {handler,writes};}
const req=body=>new Request('https://edge.invalid',{method:'POST',headers:{Authorization:'Bearer test'},body:JSON.stringify({action:'employee',kind:'quiz',...body})});
test('server saves only verified employee progress and ignores a forged score',async()=>{const h=harness(),m=exports.modules[0],answers=m.questions.map(q=>(q.answer+1)%q.options.length);const r=await h.handler(req({moduleId:m.id,answers,score:100,employeeId:'another'}));assert.equal(r.status,200);const record=h.writes[0].state.completions[0];assert.equal(record.employeeId,'own');assert.equal(record.score,0);assert.equal(record.attempts,1);});
test('passing progress is retained after a failed retry and attempts increase',async()=>{const h=harness(),m=exports.modules[0];assert.equal((await h.handler(req({moduleId:m.id,answers:m.questions.map(q=>q.answer)}))).status,200);assert.equal((await h.handler(req({moduleId:m.id,answers:m.questions.map(q=>(q.answer+1)%q.options.length)}))).status,200);const record=h.writes.at(-1).state.completions[0];assert.equal(record.score,100);assert.equal(record.attempts,2);});
test('invalid quizzes never persist progress',async()=>{const h=harness();assert.equal((await h.handler(req({moduleId:'senders',answers:[99,0,0,0,0]}))).status,400);assert.equal(h.writes.length,0);});

const require=createRequire(import.meta.url);const ui={};vm.runInNewContext(compile(readFileSync('components/training-library.tsx','utf8')),{exports:ui,require:name=>name==='@/lib/platform'?exports:require(name),setTimeout});
test('training catalog renders every lesson and exposes the PDF download',()=>{const html=renderToStaticMarkup(React.createElement(ui.default,{selectedId:null,onSelect:()=>{},employeeId:'own',completions:[],preview:false,onSubmit:async()=>80}));assert.equal((html.match(/class="panel module-card"/g)||[]).length,8);assert.ok(html.includes('/training/phishaware-training-handbook.pdf'));assert.ok(html.includes('Search training lessons'));});
test('each training page renders five questions, guidance, and an administrator preview label',()=>{for(const m of exports.modules){const html=renderToStaticMarkup(React.createElement(ui.default,{selectedId:m.id,onSelect:()=>{},employeeId:'own',completions:[],preview:true,onSubmit:async()=>{throw Error('Preview must not save');}}));assert.equal((html.match(/<fieldset/g)||[]).length,5);assert.ok(html.includes('Preview the questions. Employee progress is unchanged.'));assert.ok(html.includes('Your workplace checklist'));assert.ok(html.includes('Show suggested response'));}});
