export type Employee={id:string;name:string;email:string;department:string;active:boolean;joined:string};
export type Campaign={id:string;name:string;templateId:string;subject:string;sender:string;body:string;department:string;status:'Draft'|'Active'|'Completed';created:string;launched?:string;due:string};
export type Delivery={id:string;campaignId:string;employeeId:string;opened:boolean;clicked:boolean;reported:boolean;created:string};
export type Completion={employeeId:string;moduleId:string;score:number;attempts:number;date:string};
export type Event={id:string;actor:string;action:string;type:'Campaign'|'Employee'|'Training'|'Simulation'|'Settings';date:string};
export type Notice={id:string;employeeId:string;text:string;read:boolean;date:string};
export type Workspace={version:1;organization:string;employees:Employee[];campaigns:Campaign[];deliveries:Delivery[];completions:Completion[];events:Event[];notices:Notice[];sampleData:boolean};
export type Template={id:string;name:string;category:string;difficulty:'Beginner'|'Intermediate'|'Advanced';subject:string;sender:string;body:string;indicators:string[]};
export const templates:Template[]=[
 {id:'password',name:'Password expiry notice',category:'Credential request',difficulty:'Beginner',subject:'Action required: your password expires today',sender:'support@account-security.example.invalid',body:'Hello {{first_name}},\n\nYour account password expires at 5:00 PM today. To avoid losing access to your work files, confirm your account using the link below.\n\nThank you,\nAccount Support',indicators:['An unfamiliar sender domain','A short deadline designed to create urgency','A request to confirm account access through an unsolicited link']},
 {id:'invoice',name:'Unexpected supplier invoice',category:'Finance impersonation',difficulty:'Intermediate',subject:'Outstanding invoice: payment confirmation needed',sender:'billing@supplier-payments.example.invalid',body:'Hello {{first_name}},\n\nPlease review the outstanding invoice for your department. Payment is due today. Our banking details have changed. Use the link below to view the updated payment instructions.\n\nRegards,\nSupplier Accounts',indicators:['Unexpected payment instructions','A change of banking details','An unverified external sender']},
 {id:'benefits',name:'Employee benefits update',category:'HR impersonation',difficulty:'Intermediate',subject:'Review your updated employee benefits',sender:'people@benefits-update.example.invalid',body:'Hello {{first_name}},\n\nYour employee benefits profile needs verification. Confirm your details today to keep your benefits active for the next period.\n\nUse the link below to review your profile.\n\nPeople Operations',indicators:['A benefits-related request from an unrelated domain','Pressure to act to avoid losing benefits','An unexpected account verification link']},
 {id:'shared',name:'Shared document invitation',category:'Document sharing',difficulty:'Advanced',subject:'A confidential document was shared with you',sender:'notifications@document-access.example.invalid',body:'Hello {{first_name}},\n\nA colleague has shared a confidential planning document with you. Sign in through the secure document viewer below to review the file before the meeting.\n\nDocument Services',indicators:['The sender does not use your approved document-sharing domain','An unexpected confidential file','A sign-in request without independently verified context']}
];
export const modules=[
 {id:'senders',title:'Spot the warning signs',category:'Foundations',minutes:6,description:'Recognize suspicious senders, urgency, and unexpected requests.',sections:[{title:'Look beyond the display name',text:'A familiar name does not prove who sent a message. Inspect the complete address and domain. Compare the address with the known contact details in your organization.'},{title:'Notice pressure and unusual requests',text:'Requests for passwords, urgent payments, or unexpected confidential information deserve an independent check. Pause before following instructions.'},{title:'Verify through a trusted channel',text:'Contact the sender using a known phone number or a previously verified address. Do not use the contact details supplied in the suspicious message.'}],questions:[{prompt:'An email displays your manager’s name but uses an unfamiliar domain. What should you do?',options:['Act because the name matches','Verify through a known contact channel','Reply with your account details'],answer:1,explanation:'The display name is easy to copy. Verify the sender independently.'},{prompt:'Which request deserves extra scrutiny?',options:['A password request with an urgent deadline','A meeting listed on your existing calendar','An expected update from a verified colleague'],answer:0,explanation:'Requests for credentials combined with urgency are warning signs.'},{prompt:'Which contact method is suitable for verification?',options:['The phone number inside the suspicious email','The reply address in the suspicious email','A known number from your company directory'],answer:2,explanation:'Use an independently trusted contact method.'}]},
 {id:'links',title:'Inspect links and attachments',category:'Email safety',minutes:8,description:'Evaluate destinations and handle unexpected files safely.',sections:[{title:'Check the complete destination',text:'A brand name in a link does not mean the destination belongs to the brand. Look at the actual domain. Open services using a saved bookmark or by typing the known address.'},{title:'Treat attachments with care',text:'Verify unexpected invoices, archives and documents before opening them. Do not enable macros or install software requested by an unverified message.'},{title:'Use approved tools',text:'Follow your organization’s process for examining suspicious files. Do not upload confidential attachments to public scanning websites without approval.'}],questions:[{prompt:'An unexpected invoice asks you to enable macros. What is the safest response?',options:['Enable macros to view the invoice','Verify the invoice through a trusted contact','Send the file to all colleagues'],answer:1,explanation:'Do not enable active content in an unverified document.'},{prompt:'How should you access a service after receiving an unusual login link?',options:['Use the email link immediately','Reply asking for another link','Open your saved bookmark or known service address'],answer:2,explanation:'A known address avoids following a deceptive destination.'},{prompt:'What proves a link is safe?',options:['A familiar logo','An HTTPS padlock alone','Neither of these alone'],answer:2,explanation:'Logos are easy to copy and HTTPS encrypts connections without proving a site is trustworthy.'}]},
 {id:'report',title:'Report and respond',category:'Incident response',minutes:5,description:'Report suspicious messages and respond after an accidental click.',sections:[{title:'Report promptly',text:'Use your organization’s approved reporting process. Include the sender, subject and time. Avoid distributing the suspicious message widely.'},{title:'After following a suspicious link',text:'Stop interacting and contact your security team promptly. Explain the actions you took. Do not hide the event or delete evidence your team needs.'},{title:'If you entered credentials',text:'Change your password through the official service and follow your security team’s instructions. Review active sessions and use multifactor authentication where available.'}],questions:[{prompt:'You followed a suspicious link. What should you do next?',options:['Keep the event private','Notify your security team promptly','Delete all evidence'],answer:1,explanation:'Prompt reporting helps the team investigate and contain the incident.'},{prompt:'Where should you change a compromised password?',options:['Through the official service','On the page linked in the suspicious message','In a reply to the sender'],answer:0,explanation:'Use the official service through a known address.'},{prompt:'What information helps your security team?',options:['Only a vague description','The sender, subject, time and actions taken','Your password'],answer:1,explanation:'Provide useful context without sharing secrets.'}]},
 {id:'finance',title:'Verify payment requests',category:'Business email compromise',minutes:7,description:'Recognize impersonation and verify changes to payment details.',sections:[{title:'Recognize business impersonation',text:'Attackers impersonate managers and suppliers to request transfers, gift cards or changed account details. A familiar email conversation still needs verification when payment instructions change.'},{title:'Use a second channel',text:'Confirm unusual transactions using a trusted contact number. Follow your organization’s payment approval process even when a request appears urgent.'},{title:'Escalate irregular requests',text:'Report pressure to bypass approvals or keep a transaction secret. Preserve the message and involve finance and security staff.'}],questions:[{prompt:'A supplier announces new bank details by email. What should happen before payment?',options:['Pay immediately','Verify through a known supplier contact','Trust the message if the signature looks correct'],answer:1,explanation:'Confirm bank detail changes through an independently verified contact.'},{prompt:'Your manager requests gift cards and secrecy by email. What should you do?',options:['Purchase them quickly','Verify independently and report concerns','Send your card details'],answer:1,explanation:'Urgency and secrecy around unusual payments deserve escalation.'},{prompt:'Should an urgent email override the payment approval process?',options:['Yes, for a senior manager','Yes, near closing time','No, follow the approval process'],answer:2,explanation:'The approval process applies regardless of perceived urgency.'}]}
];
export const uid=()=>globalThis.crypto?.randomUUID?.()??Math.random().toString(36).slice(2)+Date.now().toString(36);
export const now=()=>new Date().toISOString();
export function emptyWorkspace():Workspace{return {version:1,organization:'Your organization',employees:[],campaigns:[],deliveries:[],completions:[],events:[],notices:[],sampleData:false};}
export function sampleWorkspace():Workspace{
 const w=emptyWorkspace();w.organization='Demo organization';w.sampleData=true;
 const names=[['Ama Mensah','Finance'],['Kofi Asante','Engineering'],['Abena Owusu','People Operations'],['Kwame Boateng','Operations'],['Akosua Addo','Finance'],['Yaw Osei','Engineering'],['Esi Arthur','Operations'],['Kojo Appiah','People Operations']];
 w.employees=names.map(([name,department],i)=>({id:'employee-'+i,name,email:name.toLowerCase().replace(' ','.')+'@demo.example.invalid',department,active:true,joined:'2026-09-01T09:00:00Z'}));
 for(let i=0;i<2;i++){const t=templates[i];const c:Campaign={id:'campaign-'+i,name:i?'Supplier payment verification':'September password awareness',templateId:t.id,subject:t.subject,sender:t.sender,body:t.body,department:'All departments',status:i?'Active':'Completed',created:`2026-09-${i?'24':'10'}T09:00:00Z`,launched:`2026-09-${i?'25':'12'}T09:00:00Z`,due:i?'2026-10-07':'2026-09-19'};w.campaigns.push(c);w.employees.forEach((e,j)=>w.deliveries.push({id:`delivery-${i}-${j}`,campaignId:c.id,employeeId:e.id,opened:i?j<5:true,clicked:i?j===3:j<3,reported:i?j===0:j>=3,created:c.launched!}));}
 w.employees.forEach((e,i)=>modules.slice(0,i<4?3:1).forEach(m=>w.completions.push({employeeId:e.id,moduleId:m.id,score:100,attempts:1,date:'2026-09-26T10:00:00Z'})));
 w.events=[{id:'event-1',actor:'Demo administrator',action:'Launched Supplier payment verification for 8 employees',type:'Campaign',date:'2026-09-25T09:00:00Z'},{id:'event-2',actor:'Ama Mensah',action:'Reported a suspicious simulation message',type:'Simulation',date:'2026-09-26T11:30:00Z'},{id:'event-3',actor:'Kofi Asante',action:'Completed Report and respond',type:'Training',date:'2026-09-26T10:00:00Z'}];
 w.notices=w.employees.map(e=>({id:'notice-'+e.id,employeeId:e.id,text:'A new simulation message is available in your training inbox.',read:false,date:'2026-09-25T09:00:00Z'}));return w;
}
export function percent(value:number,total:number){return total?Math.round(value/total*100):0;}
export function results(w:Workspace,employeeId?:string){const ds=w.deliveries.filter(d=>!employeeId||d.employeeId===employeeId);return {total:ds.length,opened:ds.filter(d=>d.opened).length,clicked:ds.filter(d=>d.clicked).length,reported:ds.filter(d=>d.reported).length,clickRate:percent(ds.filter(d=>d.clicked).length,ds.length),reportRate:percent(ds.filter(d=>d.reported).length,ds.length)};}
export function completionRate(w:Workspace,employeeId?:string){const people=w.employees.filter(e=>e.active&&(!employeeId||e.id===employeeId));return percent(w.completions.filter(c=>c.score>=80&&people.some(e=>e.id===c.employeeId)).length,people.length*modules.length);}
export function log(w:Workspace,actor:string,action:string,type:Event['type']){w.events.unshift({id:uid(),actor,action,type,date:now()});}
export function launchCampaign(w:Workspace,id:string,actor:string):number{
 const c=w.campaigns.find(c=>c.id===id);if(!c||c.status!=='Draft')throw Error('Only draft campaigns are available to launch.');
 const people=w.employees.filter(e=>e.active&&(c.department==='All departments'||c.department===e.department));if(!people.length)throw Error('No active employees match this department.');
 c.status='Active';c.launched=now();for(const e of people){w.deliveries.push({id:uid(),campaignId:id,employeeId:e.id,opened:false,clicked:false,reported:false,created:now()});w.notices.unshift({id:uid(),employeeId:e.id,text:`New simulation: ${c.name}`,read:false,date:now()});}log(w,actor,`Launched ${c.name} for ${people.length} employees`,'Campaign');return people.length;
}
export function recordResponse(w:Workspace,id:string,employeeId:string,action:'opened'|'clicked'|'reported'){
 const d=w.deliveries.find(d=>d.id===id&&d.employeeId===employeeId);if(!d)throw Error('This simulation message is unavailable.');
 const c=w.campaigns.find(c=>c.id===d.campaignId);if(c?.status!=='Active')throw Error('This campaign has ended. Results are read-only.');
 if(d[action])return;d[action]=true;if(action==='clicked'||action==='reported')d.opened=true;
 const e=w.employees.find(e=>e.id===employeeId)!;log(w,e.name,`${action==='reported'?'Reported':action==='clicked'?'Followed a training link in':'Opened'} ${c.name}`,'Simulation');
 if(action==='clicked')w.notices.unshift({id:uid(),employeeId,text:'Review Spot the warning signs after your recent simulation response.',read:false,date:now()});
}
export function csvCell(v:unknown){let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function reportCSV(w:Workspace){const header=['Employee','Email','Department','Messages','Opened','Clicked','Reported','Click rate (%)','Training completed (%)'];return [header,...w.employees.map(e=>{const r=results(w,e.id);return [e.name,e.email,e.department,r.total,r.opened,r.clicked,r.reported,r.clickRate,completionRate(w,e.id)];})].map(row=>row.map(csvCell).join(',')).join('\r\n');}
