'use client';
import {useState,type FormEvent} from 'react';
import {LockKeyhole,UserRound} from 'lucide-react';
import {supabase} from '@/lib/supabase';
export default function AccountSettings({email,name}:{email:string;name:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),password=String(data.get('password'));setError('');setMessage('');if(password!==data.get('confirm')){setError('The new passwords do not match.');return;}setBusy(true);try{const {error:verifyError}=await supabase.auth.signInWithPassword({email,password:String(data.get('current'))});if(verifyError)throw Error('Your current password is incorrect.');const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;form.reset();setMessage('Password updated. Use your new password next time you sign in.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="settings-grid account-settings"><section className="panel integration-panel"><div className="protection-title"><span className="protection-icon"><UserRound size={22}/></span><h2>Your profile</h2></div><dl className="profile-details"><dt>Name</dt><dd>{name}</dd><dt>Sign-in email</dt><dd>{email}</dd></dl><p>Contact your company administrator to correct your employee name or company assignment.</p></section><section className="panel integration-panel"><div className="protection-title"><span className="protection-icon"><LockKeyhole size={22}/></span><h2>Change password</h2></div><form onSubmit={changePassword}><div className="field"><label htmlFor="current-password">Current password</label><input id="current-password" name="current" className="form-input" type="password" autoComplete="current-password" required/></div><div className="field"><label htmlFor="account-password">New password</label><input id="account-password" name="password" className="form-input" type="password" autoComplete="new-password" minLength={12} required/><small>Use at least 12 characters.</small></div><div className="field"><label htmlFor="account-confirm">Confirm new password</label><input id="account-confirm" name="confirm" className="form-input" type="password" autoComplete="new-password" minLength={12} required/></div><button className="primary-button" disabled={busy}>{busy?'Updating…':'Update password'}</button></form>{error&&<p className="feedback-error" role="alert">{error}</p>}{message&&<p className="feedback-success" role="status">{message}</p>}</section></div>;
}
