'use client';
import {useState} from 'react';
import {LockKeyhole,UserRound,Mail,Building2,ShieldCheck,ChevronDown} from 'lucide-react';
import {supabase} from '@/lib/supabase';
export default function AccountSettings({email,name,company,role}:{email:string;name:string;company:string;role:string}){
 const [busy,setBusy]=useState(false),[requested,setRequested]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function requestReset(){if(!window.confirm(`Send a PhishAware password reset link to ${email}?`))return;setBusy(true);setError('');setMessage('');try{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'https://daniella-and-anthony.terkperkanthony101.workers.dev/?setup=1'});if(error)throw error;setRequested(true);setMessage('Password reset requested. Open the PhishAware email and follow the link to choose a new platform password.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="account-settings settings-grid"><section className="panel integration-panel profile-panel"><div className="protection-title"><span className="protection-icon"><UserRound size={22}/></span><div><h2>Your profile</h2><p>Your account and organization details.</p></div></div><dl className="profile-details"><div><dt><UserRound size={15}/>Name</dt><dd>{name}</dd></div><div><dt><Mail size={15}/>Email</dt><dd>{email}</dd></div><div><dt><Building2 size={15}/>Company</dt><dd>{company}</dd></div><div><dt><ShieldCheck size={15}/>Role</dt><dd><span className="profile-role">{role}</span></dd></div></dl><p className="profile-help">Contact your company administrator to correct your profile details.</p></section><section className="panel integration-panel general-options"><div className="protection-title"><span className="protection-icon"><LockKeyhole size={22}/></span><div><h2>General options</h2><p>Manage access to your PhishAware account.</p></div></div><details className="account-option"><summary><span>PhishAware password recovery</span><ChevronDown size={16}/></summary><div className="account-option-content"><p>Request an email link when you need to reset your password for this platform. This does not change your Google email password.</p><button className="outline-button" disabled={busy||requested} onClick={()=>void requestReset()}><Mail size={16}/>{busy?'Requesting…':requested?'Reset link requested':'Request platform password reset'}</button></div></details>{error&&<p className="feedback-error" role="alert">{error}</p>}{message&&<p className="feedback-success" role="status">{message}</p>}</section></div>;
}
