'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {User} from '@supabase/supabase-js';
import {supabase,passwordSetupRequested} from '@/lib/supabase';
import type {Workspace} from '@/lib/platform';
import Platform from './platform';
import MailboxSecurity,{CompanyOnboarding,EmailNotifications,useMailboxSecurity} from './mailbox-security';
import AccountSettings from './account-settings';
type Access={workspace:Workspace;revision:number;role:'Administrator'|'Employee';employeeId:string;companyId:string;platformAdmin:boolean;companies?:{id:string;name:string}[];companyAdministrators?:{email:string;status:string}[];invitations?:{email:string;status:string;last_error:string|null}[]};
async function api(body:Record<string,unknown>){const {data,error}=await supabase.functions.invoke('phishaware',{body});if(error){let message=error.message;try{const detail=await error.context?.json();message=detail?.error??message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
export default function CloudPlatform(){
 const [user,setUser]=useState<User|null>(null),[checked,setChecked]=useState(false),[access,setAccess]=useState<Access|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('Loading workspace…');
 const [returnToEmail]=useState(()=>typeof window!=='undefined'&&new URLSearchParams(window.location.search).has('state')&&(new URLSearchParams(window.location.search).has('code')||new URLSearchParams(window.location.search).has('error')));
 const [setup,setSetup]=useState(()=>passwordSetupRequested||(typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('setup')==='1')),[refresh,setRefresh]=useState(0),[companyId,setCompanyId]=useState<string|undefined>();
 const mailboxModel=useMailboxSecurity(user?.id,access?.companyId);
 const revision=useRef(0),queue=useRef(Promise.resolve()),failed=useRef(false),employeeQueue=useRef(Promise.resolve());
 useEffect(()=>{let live=true;void supabase.auth.getUser().then(({data})=>{if(live){setUser(data.user);setChecked(true);}});const {data}=supabase.auth.onAuthStateChange((event,session)=>{if(live){setUser(session?.user??null);setChecked(true);if(event==='PASSWORD_RECOVERY')setSetup(true);}});return ()=>{live=false;data.subscription.unsubscribe();};},[]);
 const signedInUserId=user?.id;
 useEffect(()=>{let live=true;void Promise.resolve().then(()=>{if(live){setAccess(null);setError('');failed.current=false;}});if(!signedInUserId)return;void api({action:'load',companyId}).then(data=>{if(live){revision.current=data.revision;setAccess(data);setStatus('Changes saved');}}).catch(e=>{if(live){setError(e.message);setStatus('Access unavailable');}});return ()=>{live=false;};},[signedInUserId,refresh,companyId]);
 function save(workspace:Workspace){if(access?.role!=='Administrator')return;setStatus('Saving…');queue.current=queue.current.then(async()=>{if(failed.current)return;const data=await api({action:'save',companyId,workspace,revision:revision.current});revision.current=data.revision;setStatus('Changes saved');}).catch(e=>{failed.current=true;setError(e.message);setStatus('Not saved');});}
 function employeeAction(action:Record<string,unknown>):Promise<Workspace>{const task=employeeQueue.current.then(async()=>{const data=await api({action:'employee',companyId,...action});revision.current=data.revision;setAccess(current=>current?{...current,...data}:current);setStatus('Changes saved');return data.workspace as Workspace;});employeeQueue.current=task.then(()=>{},()=>{});return task;}

 async function invite(ids:string[]){await queue.current;if(failed.current)throw Error('Reload and save the workspace before inviting.');const data=await api({action:'invite',companyId,employeeIds:ids});const loaded=await api({action:'load',companyId});setAccess(loaded);revision.current=loaded.revision;return data.outcomes as {email?:string;sent?:boolean;error?:string}[];}
 async function authenticate(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const f=new FormData(event.currentTarget);let email=String(f.get('email')).trim().toLowerCase();if(email==='admin')email='terkperkanthony101@gmail.com';if(email==='daniella')email='missdanikisseih@gmail.com';const {error}=await supabase.auth.signInWithPassword({email,password:String(f.get('password'))});if(error)throw error;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function setPassword(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const f=new FormData(event.currentTarget),password=String(f.get('password'));if(password!==f.get('confirm')){setError('Passwords do not match.');setBusy(false);return;}const {error}=await supabase.auth.updateUser({password});setBusy(false);if(error)setError(error.message);else{setSetup(false);history.replaceState(null,'',location.pathname);}}
 if(!checked)return <main className="panel" style={{margin:'10vh auto',maxWidth:460,padding:32}}>Checking sign-in…</main>;
 if(!user)return <main className="panel" style={{margin:'10vh auto',maxWidth:460,padding:32}}><h1>PhishAware</h1><p>Sign in with your administrator account or invited employee email.</p><form onSubmit={authenticate}><div className="field"><label htmlFor="auth-email">Email or administrator username</label><input id="auth-email" name="email" className="form-input" autoComplete="username" required/></div><div className="field"><label htmlFor="auth-password">Password</label><input id="auth-password" name="password" className="form-input" type="password" autoComplete="current-password" required/></div><button className="primary-button" disabled={busy}>{busy?'Please wait…':'Sign in'}</button></form><p role="status">{error}</p><p className="muted">Employee accounts are invitation only. Open your invitation email to set your password. Ask your administrator to resend an expired invitation.</p></main>;
 if(setup&&access)return <main className="panel" style={{margin:'10vh auto',maxWidth:460,padding:32}}><h1>Set your password</h1><p>Your verified email: {user.email}</p><form onSubmit={setPassword}><div className="field"><label htmlFor="new-password">New password</label><input id="new-password" name="password" className="form-input" type="password" minLength={12} autoComplete="new-password" required/></div><div className="field"><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" name="confirm" className="form-input" type="password" minLength={12} autoComplete="new-password" required/></div><button className="primary-button" disabled={busy}>Save password and continue</button></form><p role="alert">{error}</p></main>;
 const displayName=access?.workspace.employees.find(e=>e.id===access.employeeId)?.name??(user.email==='terkperkanthony101@gmail.com'?'Anthony':user.email==='missdanikisseih@gmail.com'?'Daniella':String(user.user_metadata?.full_name??'My account'));
 const accountHeader=error?<div className="feedback-error" role="alert">{error} <button className="text-button" onClick={()=>setRefresh(x=>x+1)}>Reload workspace</button></div>:null;
 return <>{access?<><Platform initialPage={returnToEmail?'email-protection':'overview'} accountHeader={accountHeader} accountName={displayName} saveStatus={status} onSignOut={async()=>{await queue.current;await employeeQueue.current;await supabase.auth.signOut();}} notificationCount={(access.role==='Administrator'?mailboxModel.status?.alerts?.filter(a=>a.status==='open').length:mailboxModel.status?.findings.filter(f=>f.risk!=='Low'&&f.review_state==='unreviewed').length)??0} emailProtection={<MailboxSecurity model={mailboxModel}/>} onOpenEmailProtection={async()=>{await mailboxModel.run('scan-on-open');}} notificationTools={<EmailNotifications model={mailboxModel} admin={access.role==='Administrator'}/>} accountSettings={<AccountSettings email={user.email??''} name={displayName} company={access.companies?.find(c=>c.id===access.companyId)?.name??(access.workspace.organization==='Your organization'?'Protect organization':access.workspace.organization)} role={access.role}/>} workspaceTools={<div className="workspace-tools">{access.platformAdmin&&<CompanyOnboarding companies={access.companies??[]} currentId={access.companyId} administrators={access.companyAdministrators??[]} onSelect={async id=>{await queue.current;if(failed.current){setError('Reload before switching companies.');return;}setCompanyId(id);}} onCreate={async(name,adminEmail)=>{await queue.current;if(failed.current)throw Error('Reload before creating a company.');const data=await api({action:'create-company',name,adminEmail});setCompanyId(data.companyId);}} onInvite={async email=>{await api({action:'invite-admin',companyId:access.companyId,email});setRefresh(x=>x+1);}}/>}</div>} key={user.id+':'+access.companyId} initialWorkspace={access.workspace} onWorkspaceChange={save} accountRole={access.role} assignedEmployeeId={access.employeeId} onEmployeeAction={employeeAction} onInvite={invite} invitations={access.invitations??[]}/></>:<main className="panel" style={{margin:32,padding:24}}>{accountHeader}{error?'Access is restricted to approved administrators and invited employees.':'Loading your workspace…'}</main>}</>;
}
