'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {User} from '@supabase/supabase-js';
import {supabase} from '@/lib/supabase';
import {emptyWorkspace,type Workspace} from '@/lib/platform';
import Platform from './platform';
export default function CloudPlatform(){
 const [user,setUser]=useState<User|null>(null),[checked,setChecked]=useState(false),[workspace,setWorkspace]=useState<Workspace|null>(null);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[signup,setSignup]=useState(false),[status,setStatus]=useState('Loading workspace…');
 const revision=useRef(0),queue=useRef(Promise.resolve()),failed=useRef(false);
 useEffect(()=>{let live=true;void supabase.auth.getUser().then(({data})=>{if(live){setUser(data.user);setChecked(true);}});const {data}=supabase.auth.onAuthStateChange((_event,session)=>{if(live){setUser(session?.user??null);setChecked(true);}});return ()=>{live=false;data.subscription.unsubscribe();};},[]);
 useEffect(()=>{let live=true;setWorkspace(null);revision.current=0;failed.current=false;if(!user)return;void (async()=>{const {data,error}=await supabase.from('phishaware_workspaces').select('state,revision').eq('owner_id',user.id).maybeSingle();if(!live)return;if(error){setError(error.message);return;}if(data){revision.current=data.revision;setWorkspace(data.state as Workspace);}else{const state=emptyWorkspace();const {error}=await supabase.from('phishaware_workspaces').insert({owner_id:user.id,state});if(!live)return;if(error){setError(error.message);return;}revision.current=1;setWorkspace(state);}setStatus('Saved to Supabase');})();return ()=>{live=false;};},[user?.id]);
 function save(state:Workspace){if(!user)return;const owner=user.id;setStatus('Saving…');queue.current=queue.current.then(async()=>{if(failed.current)return;const old=revision.current;const {data,error}=await supabase.from('phishaware_workspaces').update({state,revision:old+1,updated_at:new Date().toISOString()}).eq('owner_id',owner).eq('revision',old).select('revision').maybeSingle();if(error||!data){failed.current=true;setStatus('Not saved');setError(error?.message??'This workspace changed in another browser. Reload before making more changes.');return;}revision.current=data.revision;setStatus('Saved to Supabase');}).catch(()=>{failed.current=true;setStatus('Not saved');setError('Connection interrupted. Reload and check your saved workspace.');});}
 async function authenticate(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const credentials={email:String(form.get('email')).trim(),password:String(form.get('password'))};const result=signup?await supabase.auth.signUp(credentials):await supabase.auth.signInWithPassword(credentials);setBusy(false);if(result.error)setError(result.error.message);else if(signup&&!result.data.session)setError('Check your email to confirm your account, then return here to sign in.');}
 if(!checked)return <main className="panel" style={{margin:'10vh auto',maxWidth:460,padding:32}}>Checking sign-in…</main>;
 if(!user)return <main className="panel" style={{margin:'10vh auto',maxWidth:460,padding:32}}><h1>PhishAware</h1><p>Sign in to your private awareness workspace.</p><form onSubmit={authenticate}><div className="field"><label htmlFor="auth-email">Email</label><input id="auth-email" name="email" className="form-input" type="email" autoComplete="email" required/></div><div className="field"><label htmlFor="auth-password">Password</label><input id="auth-password" name="password" className="form-input" type="password" autoComplete={signup?'new-password':'current-password'} minLength={8} required/></div><button className="primary-button" disabled={busy}>{busy?'Please wait…':signup?'Create private workspace':'Sign in'}</button></form><p role="status">{error}</p><button className="text-button" onClick={()=>{setSignup(!signup);setError('');}}>{signup?'Already registered? Sign in':'Create an account'}</button><p className="muted">Each account owns a separate workspace. Employee account invitations are not enabled yet.</p></main>;
 return <><div style={{padding:'12px 24px',background:'#eff6ff',display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}><span>{user.email}</span><strong role="status">{status}</strong><button className="text-button" onClick={async()=>{await queue.current;const {error}=await supabase.auth.signOut();if(error)setError(error.message);}}>Sign out</button>{error&&<span role="alert" style={{color:'#b91c1c'}}>{error} <button onClick={()=>location.reload()}>Reload workspace</button></span>}</div>{workspace?<Platform key={user.id} initialWorkspace={workspace} onWorkspaceChange={save}/>:<main className="panel" style={{margin:32,padding:24}}>Loading your workspace… {error}</main>}</>;
}
