'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {ShieldCheck,TriangleAlert,Flag,CheckCircle2,RefreshCw,Mail,Bell,ExternalLink} from 'lucide-react';
import {supabase} from '@/lib/supabase';
export type Finding={message_id:string;subject:string;sender:string;received_at:string;risk:'Low'|'Medium'|'High';reasons:string[];recommendation:string;review_state:'unreviewed'|'reviewed'|'reported'};
type Alert={id:string;employee_email:string;subject:string;sender:string;risk:'Low'|'Medium'|'High';reasons:string[];recommendation:string;source:'automatic'|'employee';status:'open'|'resolved';created_at:string};
type Status={configured:boolean;automaticScanning:boolean;connection:null|{email:string;status:string;lastScanAt:string|null;lastError:string|null};findings:Finding[];alerts:Alert[]};
async function mailbox(action:string,extra:Record<string,unknown>={}){const {data,error}=await supabase.functions.invoke('mailbox-security',{body:{action,...extra}});if(error){let message=error.message;try{message=(await error.context?.json()).error??message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
export function useMailboxSecurity(userId:string|undefined,companyId:string|undefined){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[updated,setUpdated]=useState<Date|null>(null);
 const generation=useRef(0),loading=useRef(false);
 const load=useCallback(async()=>{if(!userId||loading.current)return;loading.current=true;const current=generation.current;try{const data=await mailbox('status',{companyId});if(current===generation.current){setStatus(data);setUpdated(new Date());setError('');}}catch(e){if(current===generation.current)setError((e as Error).message);}finally{loading.current=false;}},[userId,companyId]);
 useEffect(()=>{const effectGeneration=++generation.current;let live=true;if(!userId)return()=>{live=false;if(generation.current===effectGeneration)generation.current=effectGeneration+1;};const query=new URLSearchParams(location.search);async function init(){await Promise.resolve();if(!live)return;setStatus(null);setError('');setMessage('');if(query.has('state')&&(query.has('code')||query.has('error'))){const code=query.get('code'),state=query.get('state');history.replaceState(null,'',location.pathname);try{if(!code)throw Error('Google connection was cancelled.');await mailbox('complete',{code,state});if(live)setMessage('Mailbox connected. Your first scan will start automatically.');}catch(e){if(live)setError((e as Error).message);}}if(live)await load();}void init();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{live=false;if(generation.current===effectGeneration)generation.current=effectGeneration+1;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[userId,load]);
 async function run(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');setMessage('');try{if(action==='connect'){const data=await mailbox('connect');const url=new URL(data.url);if(url.origin!=='https://accounts.google.com')throw Error('Invalid authorization destination.');location.assign(url.href);return;}if(action==='disconnect'&&!window.confirm('Disconnect Google and remove stored findings and shared alerts?'))return;if(action==='review'&&extra.decision==='reported'&&!window.confirm('Share this email’s sender, subject, risk summary, and your email address with your company administrators? Message bodies and attachments are excluded.'))return;const result=await mailbox(action,{companyId,...extra});setMessage(action==='review'?extra.decision==='reported'?'Reported to your company administrators.':'Review saved. This does not certify the email as safe.':action==='resolve-alert'?'Alert resolved.':action==='disconnect'?'Mailbox disconnected. Stored findings and alerts removed.':result.busy?'A scan is already running.':`Checked ${result.processed} new messages.${result.backlog?' More messages are waiting for the next scan.':''}`);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return {status,busy,error,message,updated,load,run};
}
export type MailboxModel=ReturnType<typeof useMailboxSecurity>;
function Feedback({model}:{model:MailboxModel}){return <>{model.error&&<p className="feedback-error" role="alert">{model.error}</p>}{model.message&&<p className="feedback-success" role="status">{model.message}</p>}</>;}
export default function MailboxSecurity({model,settings=false}:{model:MailboxModel;settings?:boolean}){
 const {status,busy,load,run,updated}=model;const [consent,setConsent]=useState(false),[filter,setFilter]=useState('All'),[expanded,setExpanded]=useState(false);
 const findings=status?.findings??[],visible=findings.filter(f=>filter==='All'?true:filter==='Needs review'?f.review_state==='unreviewed':f.risk===filter);
 return <section className="panel integration-panel email-protection" aria-label="Email protection"><div className="protection-heading"><div className="protection-title"><span className="protection-icon"><ShieldCheck size={22}/></span><div><h2>{settings?'Google mailbox connection':'Email protection'}</h2><p>Review warning signs and decide your next action.</p></div></div><span className={'connection-pill '+(status?.connection?.status==='connected'?'connected':'')}>{status?.connection?.status==='connected'?'Connected':status?.connection?'Reconnect required':'Not connected'}</span></div>
 {!status?<p>Loading email protection…</p>:<>{status.connection?<><div className="mailbox-meta"><span><Mail size={15}/>{status.connection.email}</span><span><RefreshCw size={14}/>Last scan: {status.connection.lastScanAt?new Date(status.connection.lastScanAt).toLocaleTimeString():'Starting'}</span></div><p className="scan-hint">{status.automaticScanning?'Automatic checks are active. Results refresh every 15 seconds while this page is open.':'Manual checks are available. Automatic checks are awaiting setup.'}</p><div className="integration-actions"><button className="primary-button" disabled={busy||status.connection.status!=='connected'} onClick={()=>void run('scan')}><ShieldCheck size={16}/>{busy?'Working…':'Scan now'}</button><button className="outline-button" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/>Refresh results</button>{settings&&<button className="outline-button danger-button" disabled={busy} onClick={()=>void run('disconnect')}>Disconnect Google</button>}</div>{status.connection.lastError&&<p className="feedback-error" role="alert">{status.connection.lastError}</p>}</>:<><p>Connect your invited Google account for automatic email checks.</p><label className="mailbox-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to mailbox scanning and sharing High risk summaries with my company administrators.</span></label><button className="primary-button" disabled={busy||!consent||!status.configured} onClick={()=>void run('connect')}>Connect Google email</button>{!status.configured&&<p>Google connection setup is incomplete. Contact your platform administrator.</p>}</>}
 <details className="privacy-details"><summary>How scanning and reporting use your data</summary><p>PhishAware reads message text and attachment names. Message bodies and attachments are not stored. High risk findings automatically notify your company administrators with your email, sender, subject, risk reasons, and suggested action. Selecting Report suspicious shares the same summary for any finding. Administrators do not receive mailbox access. Stored findings and alerts are deleted after 30 days by the cleanup schedule, or when you disconnect Google.</p><p>Content rules estimate risk. Sender authenticity, linked websites, and attachment contents are not verified. Low risk and a saved review do not guarantee safety.</p></details>
 {!settings&&status.connection&&<><div className="finding-toolbar"><div><h3>Recent email checks</h3><p>{findings.length} results{updated?` · Updated ${updated.toLocaleTimeString()}`:''}</p></div><label className="sr-only" htmlFor="risk-filter">Filter email checks</label><select id="risk-filter" className="form-input" value={filter} onChange={e=>{setFilter(e.target.value);setExpanded(false);}}>{['All','Needs review','High','Medium','Low'].map(v=><option key={v}>{v}</option>)}</select></div><div className="findings-list">{visible.slice(0,expanded?100:5).map(f=><article className={'finding-card risk-'+f.risk.toLowerCase()} key={f.message_id}><div className="finding-top"><span className={'risk-pill '+f.risk.toLowerCase()}>{f.risk==='High'?<TriangleAlert size={14}/>:<ShieldCheck size={14}/>} {f.risk} risk</span><span className="review-label">{f.review_state==='reported'?'Reported':f.review_state==='reviewed'?'Reviewed':'Awaiting review'}</span></div><h3>{f.subject||'(No subject)'}</h3><p className="finding-sender">{f.sender}</p><time>{new Date(f.received_at).toLocaleString()}</time><ul>{f.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><p className="next-action"><strong>Suggested action</strong>{f.recommendation}</p>{f.risk==='High'&&<p className="shared-notice"><Bell size={14}/>High risk summary shared with company administrators.</p>}<div className="finding-actions"><button className="outline-button" disabled={busy||f.review_state==='reviewed'} onClick={()=>void run('review',{messageId:f.message_id,decision:'reviewed'})}><CheckCircle2 size={16}/>Save as reviewed</button><button className="report-button" disabled={busy||f.review_state==='reported'} onClick={()=>void run('review',{messageId:f.message_id,decision:'reported'})}><Flag size={16}/>{f.review_state==='reported'?'Reported':'Report suspicious'}</button><a className="text-button" href="https://mail.google.com/mail/u/0/#inbox" target="_blank" rel="noopener noreferrer">Open Gmail <ExternalLink size={14}/></a></div></article>)}</div>{!visible.length&&<div className="notification-empty"><ShieldCheck size={28}/><h3>{findings.length?'No matching emails':'Waiting for the first scan'}</h3><p>{findings.length?'Choose another filter to view your results.':'Results will appear here automatically after your next scan.'}</p></div>}{visible.length>5&&<button className="outline-button results-toggle" onClick={()=>setExpanded(v=>!v)}>{expanded?'Show fewer emails':`Show all ${visible.length} emails`}</button>}</>}</>}<Feedback model={model}/></section>;
}
export function EmailNotifications({model,admin}:{model:MailboxModel;admin:boolean}){
 const {status,busy,run}=model;const [showResolved,setShowResolved]=useState(false);
 const alerts=(status?.alerts??[]).filter(a=>showResolved||a.status==='open');
 const findings=(status?.findings??[]).filter(f=>f.risk!=='Low'&&f.review_state==='unreviewed');
 return <section className="panel integration-panel"><div className="protection-heading"><div className="protection-title"><span className="protection-icon"><Bell size={22}/></span><div><h2>{admin?'Company email alerts':'Email risk updates'}</h2><p>{admin?'High risk findings and employee reports needing attention.':'Warnings from your connected mailbox.'}</p></div></div>{admin&&<label className="notification-toggle"><input type="checkbox" checked={showResolved} onChange={e=>setShowResolved(e.target.checked)}/>Include resolved</label>}</div>{!status?<p>Loading notifications…</p>:admin?alerts.length?alerts.map(a=><article className="alert-card" key={a.id}><div className="finding-top"><span className={'risk-pill '+a.risk.toLowerCase()}>{a.risk} risk</span><span className="review-label">{a.status==='resolved'?'Resolved':a.source==='automatic'?'Automatic alert':'Employee report'}</span></div><h3>{a.subject||'(No subject)'}</h3><p>Reported account: {a.employee_email}</p><p>Sender: {a.sender}</p><time>{new Date(a.created_at).toLocaleString()}</time><ul>{a.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><p className="next-action"><strong>Suggested action</strong>{a.recommendation}</p>{a.status==='open'&&<button className="outline-button" disabled={busy} onClick={()=>void run('resolve-alert',{alertId:a.id})}><CheckCircle2 size={16}/>Mark resolved</button>}</article>):<div className="notification-empty"><CheckCircle2 size={28}/><h3>No open email alerts</h3><p>New High risk findings and employee reports will appear here.</p></div>:findings.length?findings.map(f=><article className="alert-card" key={f.message_id}><span className={'risk-pill '+f.risk.toLowerCase()}>{f.risk} risk</span><h3>{f.subject||'(No subject)'}</h3><p>{f.recommendation}</p><button className="report-button" disabled={busy} onClick={()=>void run('review',{messageId:f.message_id,decision:'reported'})}><Flag size={16}/>Report suspicious</button></article>):<div className="notification-empty"><CheckCircle2 size={28}/><h3>You’re up to date</h3><p>No email warnings are waiting for your review.</p></div>}<Feedback model={model}/></section>;
}
export function CompanyOnboarding({companies,currentId,onSelect,onCreate,onInvite,administrators}:{companies:{id:string;name:string}[];currentId:string;onSelect:(id:string)=>void;onCreate:(name:string,email:string)=>Promise<void>;onInvite:(email:string)=>Promise<void>;administrators:{email:string;status:string}[]}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget,data=new FormData(form);try{await onCreate(String(data.get('name')),String(data.get('email')));form.reset();setMessage('Company created. Select Invite administrator below to send their password setup email.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel integration-panel"><h2>Company onboarding</h2><label className="company-selector">Company workspace <select className="form-input" value={currentId} disabled={busy} onChange={e=>onSelect(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>Each employee account belongs to one company. Company administrators manage their own staff, simulations, and training.</p><form onSubmit={create} className="company-form"><label>Company name<input name="name" className="form-input" required minLength={2} maxLength={100}/></label><label>Company administrator email<input name="email" className="form-input" type="email" required/></label><button className="primary-button" disabled={busy}>Create company</button></form>{administrators.map(a=><div key={a.email} className="company-admin-row">{a.email} · {a.status} <button className="outline-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onInvite(a.email);setMessage(`Administrator setup email sent to ${a.email}.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Invite administrator</button></div>)}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
