'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {ShieldCheck,TriangleAlert,Flag,CheckCircle2,RefreshCw,Mail,Bell,ExternalLink} from 'lucide-react';
import {supabase} from '@/lib/supabase';
export type Finding={message_id:string;subject:string;sender:string;received_at:string;risk:'Low'|'Medium'|'High';reasons:string[];recommendation:string;notification_read:boolean;review_outcome?:'safe'|'action_taken'|null;review_note?:string|null;admin_reviewed_at?:string|null;review_state:'unreviewed'|'reviewed'|'reported'};
type Alert={id:string;employee_email:string;subject:string;sender:string;risk:'Low'|'Medium'|'High';reasons:string[];recommendation:string;request_kind?:'review'|'report';review_outcome?:'safe'|'action_taken'|null;review_note?:string|null;resolved_at?:string|null;source:'automatic'|'employee';notification_read:boolean;status:'open'|'resolved';created_at:string};
type Status={notificationCount:number;emailAlertsConfigured:boolean;configured:boolean;automaticScanning:boolean;connection:null|{email:string;status:string;lastScanAt:string|null;lastError:string|null};findings:Finding[];alerts:Alert[]};
async function mailbox(action:string,extra:Record<string,unknown>={}){const {data,error}=await supabase.functions.invoke('mailbox-security',{body:{action,...extra}});if(error){let message=error.message;try{message=(await error.context?.json()).error??message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
export function useMailboxSecurity(userId:string|undefined,companyId:string|undefined){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[updated,setUpdated]=useState<Date|null>(null);
 const generation=useRef(0),loading=useRef(false);
 const invalidate=useCallback(()=>{generation.current+=1;},[]);
 const load=useCallback(async()=>{if(!userId||loading.current)return;loading.current=true;const current=generation.current;try{const data=await mailbox('status',{companyId});if(current===generation.current){setStatus(data);setUpdated(new Date());setError('');}}catch(e){if(current===generation.current)setError((e as Error).message);}finally{loading.current=false;}},[userId,companyId]);
 useEffect(()=>{invalidate();let live=true;if(!userId)return()=>{live=false;invalidate();};const query=new URLSearchParams(location.search);async function init(){await Promise.resolve();if(!live)return;setStatus(null);setError('');setMessage('');if(query.has('state')&&(query.has('code')||query.has('error'))){const code=query.get('code'),state=query.get('state');history.replaceState(null,'',location.pathname);try{if(!code)throw Error('Google connection was cancelled.');await mailbox('complete',{code,state});if(live)setMessage('Mailbox connected. Your first scan will start automatically.');}catch(e){if(live)setError((e as Error).message);}}if(live)await load();}void init();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{live=false;invalidate();clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[userId,load,invalidate]);
 async function run(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');setMessage('');try{if(action==='connect'){const data=await mailbox('connect');const url=new URL(data.url);if(url.origin!=='https://accounts.google.com')throw Error('Invalid authorization destination.');location.assign(url.href);return;}if(action==='disconnect'&&!window.confirm('Disconnect Google and remove stored findings and shared alerts?'))return;if(action==='review'&&!window.confirm('Share this email’s sender, subject, risk summary, and your email address with your company administrators? Message bodies and attachments are excluded.'))return;const result=await mailbox(action,{companyId,...extra});if(action==='read-notification'){invalidate();setStatus(current=>current?{...current,notificationCount:extra.all?0:Math.max(0,current.notificationCount-1),findings:current.findings.map(f=>extra.all||f.message_id===extra.messageId?{...f,notification_read:true}:f),alerts:current.alerts.map(a=>extra.all||a.id===extra.alertId?{...a,notification_read:true}:a)}:current);}
setMessage(action==='read-notification'?'Notifications marked as read.':action==='review'?extra.decision==='reported'?'Reported to your company administrators.':'Sent to your company administrators for review. You will receive their decision in Notifications.':action==='resolve-alert'?'Review completed. The employee has been notified.':action==='disconnect'?'Mailbox disconnected. Stored findings and alerts removed.':result.notConnected?'':result.recent?'Showing your latest scan. Automatic checks continue in the background.':result.busy?'A scan is already running.':`Checked ${result.processed} new messages.${result.backlog?' More messages are waiting for the next scan.':''}`);await load();}catch(e){setError((e as Error).message);if(action==='read-notification')throw e;}finally{setBusy(false);}}
 return {status,busy,error,message,updated,load,run};
}
export type MailboxModel=ReturnType<typeof useMailboxSecurity>;
function Feedback({model}:{model:MailboxModel}){return <>{model.error&&<p className="feedback-error" role="alert">{model.error}</p>}{model.message&&<p className="feedback-success" role="status">{model.message}</p>}</>;}
export default function MailboxSecurity({model,settings=false}:{model:MailboxModel;settings?:boolean}){
 const {status,busy,load,run,updated}=model;const [consent,setConsent]=useState(false),[filter,setFilter]=useState('All'),[expanded,setExpanded]=useState(false);
 const findings=status?.findings??[],visible=findings.filter(f=>filter==='All'?true:filter==='Needs review'?f.review_state==='unreviewed':f.risk===filter);
 return <section className="panel integration-panel email-protection google-mailbox" aria-label="Email protection"><div className="google-colour-bar" aria-hidden="true"><span/><span/><span/><span/></div><div className="protection-heading"><div className="protection-title"><span className="protection-icon"><ShieldCheck size={22}/></span><div><h2>{settings?'Google mailbox connection':'Email protection'}</h2><p>Your Google mailbox, reviewed in PhishAware.</p></div></div><span className={'connection-pill '+(status?.connection?.status==='connected'?'connected':'')}>{status?.connection?.status==='connected'?'Connected':status?.connection?'Reconnect required':'Not connected'}</span></div>
 {!status?<p>Loading email protection…</p>:<>{status.connection?<><div className="mailbox-meta"><span><Mail size={15}/>{status.connection.email}</span><span><RefreshCw size={14}/>Last scan: {status.connection.lastScanAt?new Date(status.connection.lastScanAt).toLocaleTimeString():'Starting'}</span></div><p className="scan-hint">{status.automaticScanning?'Automatic checks are active. Results refresh every 15 seconds while this page is open.':'Manual checks are available. Automatic checks are awaiting setup.'}</p><div className="integration-actions"><button className="primary-button" disabled={busy||status.connection.status!=='connected'} onClick={()=>void run('scan')}><ShieldCheck size={16}/>{busy?'Working…':'Scan now'}</button><button className="outline-button" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/>Refresh results</button>{<button className="outline-button danger-button" disabled={busy} onClick={()=>void run('disconnect')}>Disconnect Google</button>}</div>{status.connection.lastError&&<p className="feedback-error" role="alert">{status.connection.lastError}</p>}</>:<><p>Connect your invited Google account for automatic email checks.</p><label className="mailbox-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to mailbox scanning and sharing High risk summaries with my company administrators.</span></label><button className="primary-button" disabled={busy||!consent||!status.configured} onClick={()=>void run('connect')}>Connect Google email</button>{!status.configured&&<p>Google connection setup is incomplete. Contact your platform administrator.</p>}</>}
 <details className="privacy-details"><summary>How scanning and reporting use your data</summary><p>PhishAware reads message text and attachment names. Message bodies and attachments are not stored. High risk findings automatically notify your company administrators with your email, sender, subject, risk reasons, and suggested action. Selecting Save for review or Report issue shares the same summary for any finding. Administrators review the summary and send their decision to your Notifications. Administrators do not receive mailbox access. Scan findings and shared alerts are deleted after 30 days by the cleanup schedule. Your notification history keeps risk summaries until you disconnect Google. Disconnecting removes findings, alerts, and notification history.</p><p>Content rules estimate risk. Sender authenticity, linked websites, and attachment contents are not verified. Low risk and a saved review do not guarantee safety.</p></details>
 {!settings&&status.connection&&<><div className="finding-toolbar"><div><h3>Recent email checks</h3><p>{findings.length} results{updated?` · Updated ${updated.toLocaleTimeString()}`:''}</p></div><label className="sr-only" htmlFor="risk-filter">Filter email checks</label><select id="risk-filter" className="form-input" value={filter} onChange={e=>{setFilter(e.target.value);setExpanded(false);}}>{['All','Needs review','High','Medium','Low'].map(v=><option key={v}>{v}</option>)}</select></div><div className="findings-list">{visible.slice(0,expanded?100:5).map(f=><article className={'finding-card risk-'+f.risk.toLowerCase()} key={f.message_id}><div className="finding-top"><span className={'risk-pill '+f.risk.toLowerCase()}>{f.risk==='High'?<TriangleAlert size={14}/>:<ShieldCheck size={14}/>} {f.risk} risk</span><span className="review-label">{f.review_outcome==='safe'?'Administrator marked safe':f.review_outcome==='action_taken'?'Action taken':f.review_state==='reported'?'Reported to administrators':f.review_state==='reviewed'?'Sent for administrator review':'Not sent for review'}</span></div><h3>{f.subject||'(No subject)'}</h3><p className="finding-sender">{f.sender}</p><time>{new Date(f.received_at).toLocaleString()}</time><ul>{f.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><p className="next-action"><strong>Suggested action</strong>{f.recommendation}</p>{f.risk==='High'&&<p className="shared-notice"><Bell size={14}/>High risk summary shared with company administrators.</p>}<ReviewOutcome finding={f}/><div className="finding-actions"><button className="outline-button save-review-button" disabled={busy||f.review_state!=='unreviewed'||!!f.review_outcome} onClick={()=>void run('review',{messageId:f.message_id,decision:'reviewed'})}><CheckCircle2 size={16}/>{f.review_state==='unreviewed'?'Save for review':'Sent for review'}</button><button className="report-button" disabled={busy||f.review_state==='reported'||!!f.review_outcome} onClick={()=>void run('review',{messageId:f.message_id,decision:'reported'})}><Flag size={16}/>{f.review_state==='reported'?'Reported':'Report issue'}</button><a className="text-button" href="https://mail.google.com/mail/u/0/#inbox" target="_blank" rel="noopener noreferrer">Open Gmail <ExternalLink size={14}/></a></div></article>)}</div>{!visible.length&&<div className="notification-empty"><ShieldCheck size={28}/><h3>{findings.length?'No matching emails':'Waiting for the first scan'}</h3><p>{findings.length?'Choose another filter to view your results.':'Results will appear here automatically after your next scan.'}</p></div>}{visible.length>5&&<button className="outline-button results-toggle" onClick={()=>setExpanded(v=>!v)}>{expanded?'Show fewer emails':`Show all ${visible.length} emails`}</button>}</>}</>}<Feedback model={model}/></section>;
}
function ReviewOutcome({finding}:{finding:Pick<Finding,'review_outcome'|'review_note'|'admin_reviewed_at'>}){
 if(!finding.review_outcome)return null;
 return <div className={'admin-review-result '+(finding.review_outcome==='safe'?'review-safe':'review-action')}><strong><CheckCircle2 size={16}/>{finding.review_outcome==='safe'?'Marked safe by your administrator':'Reviewed. Action taken.'}</strong>{finding.review_note&&<p>{finding.review_note}</p>}{finding.admin_reviewed_at&&<time>Reviewed {new Date(finding.admin_reviewed_at).toLocaleString()}</time>}<p className="review-rating-note">The original automated risk rating is retained for your records.</p></div>;
}
function AdminReviewActions({alert,model}:{alert:Alert;model:MailboxModel}){
 const [note,setNote]=useState('');
 function finish(outcome:'safe'|'action_taken'){
  if(outcome==='safe'&&!window.confirm('Confirm you have reviewed this email and consider it safe. The employee will receive your decision.'))return;
  void model.run('resolve-alert',{alertId:alert.id,outcome,note});
 }
 return <div className="admin-review-controls"><label>Review note for the employee<textarea className="form-input" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain your decision or the action taken."/></label><div className="finding-actions"><button className="primary-button" disabled={model.busy} onClick={()=>finish('safe')}><ShieldCheck size={16}/>Mark safe</button><button className="outline-button" disabled={model.busy||note.trim().length<3} onClick={()=>finish('action_taken')}><CheckCircle2 size={16}/>Action taken</button></div><p className="muted">Your decision and note will appear in the employee’s Notifications. Record the action before closing an unsafe email report.</p></div>;
}
export function EmailNotifications({model,admin}:{model:MailboxModel;admin:boolean}){
 const {status,busy,run}=model;const [showResolved,setShowResolved]=useState(false);
 const alerts=(status?.alerts??[]).filter(a=>showResolved||(a.status==='open'));
 const findings=(status?.findings??[]).filter(f=>f.risk!=='Low'&&f.review_state==='unreviewed'&&!f.notification_read);
 if(!admin)return <EmployeeEmailHistory model={model}/>;
 return <section className="panel integration-panel"><div className="protection-heading"><div className="protection-title"><span className="protection-icon"><Bell size={22}/></span><div><h2>{admin?'Company email alerts':'Email risk updates'}</h2><p>{admin?'Review employee requests and reports, then send a decision.':'Warnings from your connected mailbox.'}</p></div></div>{admin&&<label className="notification-toggle"><input type="checkbox" checked={showResolved} onChange={e=>setShowResolved(e.target.checked)}/>Include read and resolved</label>}</div>{!status?<p>Loading notifications…</p>:admin?alerts.length?alerts.map(a=><article className="alert-card" key={a.id}><div className="finding-top"><span className={'risk-pill '+a.risk.toLowerCase()}>{a.risk} risk</span><span className="review-label">{a.status==='resolved'?'Resolved':a.source==='automatic'?'Automatic alert':a.request_kind==='review'?'Review requested':'Employee report'}</span></div><h3>{a.subject||'(No subject)'}</h3><p>Reported account: {a.employee_email}</p><p>Sender: {a.sender}</p><time>{new Date(a.created_at).toLocaleString()}</time><ul>{a.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><p className="next-action"><strong>Suggested action</strong>{a.recommendation}</p>{!a.notification_read&&<button className="text-button" disabled={busy} onClick={()=>void run('read-notification',{alertId:a.id}).catch(()=>{})}>Mark as read</button>}{a.status==='open'?<AdminReviewActions alert={a} model={model}/>:<ReviewOutcome finding={{review_outcome:a.review_outcome,review_note:a.review_note,admin_reviewed_at:a.resolved_at}}/>}</article>):<div className="notification-empty"><CheckCircle2 size={28}/><h3>No open email alerts</h3><p>New High risk findings and employee reports will appear here.</p></div>:findings.length?findings.map(f=><article className="alert-card" key={f.message_id}><span className={'risk-pill '+f.risk.toLowerCase()}>{f.risk} risk</span><h3>{f.subject||'(No subject)'}</h3><p>{f.recommendation}</p><button className="outline-button" disabled={busy} onClick={()=>void run('read-notification',{messageId:f.message_id}).catch(()=>{})}>Mark as read</button><button className="report-button" disabled={busy} onClick={()=>void run('review',{messageId:f.message_id,decision:'reported'})}><Flag size={16}/>Report suspicious</button></article>):<div className="notification-empty"><CheckCircle2 size={28}/><h3>You’re up to date</h3><p>No email warnings are waiting for your review.</p></div>}<Feedback model={model}/></section>;
}
function EmployeeEmailHistory({model}:{model:MailboxModel}){
 const [history,setHistory]=useState(false),[query,setQuery]=useState(''),[page,setPage]=useState(0),[items,setItems]=useState<Finding[]>([]),[hasMore,setHasMore]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{if(live)setLoading(true);void mailbox('notifications',{history,query,page}).then(data=>{if(live){setItems(data.items);setHasMore(data.hasMore);setError('');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});},250);return()=>{live=false;clearTimeout(timer);};},[history,query,page,model.status]);
 return <section className="panel integration-panel"><h2>Email notifications</h2><p>Read notifications stay in History for future searches.</p><div className="notification-history-controls"><div className="period-tabs"><button className={!history?'selected':''} aria-pressed={!history} onClick={()=>{setHistory(false);setPage(0);}}>Active</button><button className={history?'selected':''} aria-pressed={history} onClick={()=>{setHistory(true);setPage(0);}}>History</button></div><input className="form-input" aria-label="Search email notifications" placeholder="Search subject, sender, or guidance" maxLength={100} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div>{loading?<p role="status">Loading notifications…</p>:items.length?items.map(f=><article className="alert-card" key={f.message_id}><span className={'risk-pill '+f.risk.toLowerCase()}>{f.risk} risk</span><h3>{f.subject||'(No subject)'}</h3><p>{f.sender}</p><time>{new Date(f.received_at).toLocaleString()}</time><ul>{f.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><p>{f.recommendation}</p><ReviewOutcome finding={f}/>{!history&&<button className="outline-button" disabled={model.busy} onClick={()=>void model.run('read-notification',{messageId:f.message_id}).then(()=>setItems(items=>items.filter(i=>i.message_id!==f.message_id))).catch(()=>{})}>Mark as read</button>}{!f.review_outcome&&model.status?.findings.some(i=>i.message_id===f.message_id&&i.review_state!=='reported')&&<button className="report-button" disabled={model.busy} onClick={()=>void model.run('review',{messageId:f.message_id,decision:'reported'})}><Flag size={16}/>Report suspicious</button>}</article>):<div className="notification-empty"><CheckCircle2 size={28}/><h3>{history?'No matching history':'You’re up to date'}</h3><p>{history?'Try a different search.':'Read notifications are available in History.'}</p></div>}<div className="audit-pagination"><button className="outline-button" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button className="outline-button" disabled={!hasMore||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div><p className="muted">Notification summaries are retained until you disconnect your mailbox. Full email bodies and attachments are excluded.</p>{error&&<p className="feedback-error" role="alert">{error}</p>}<Feedback model={model}/></section>;
}
export function CompanyOnboarding({companies,currentId,onSelect,onCreate,onInvite,onInviteEmployee,employees,invitations,administrators}:{companies:{id:string;name:string}[];currentId:string;onSelect:(id:string)=>void;onCreate:(name:string,personName:string,email:string)=>Promise<void>;onInvite:(email:string)=>Promise<void>;onInviteEmployee:(id:string)=>Promise<void>;employees:{id:string;name:string;email:string;active:boolean}[];invitations:{email:string;status:string}[];administrators:{email:string;status:string}[]}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget,data=new FormData(form);try{await onCreate(String(data.get('name')),String(data.get('personName')),String(data.get('email')));form.reset();setMessage('Organization created. Select Send invite below to invite the employee.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function send(email:string,id?:string){setBusy(true);setError('');try{if(id)await onInviteEmployee(id);else await onInvite(email);setMessage(`Invitation sent to ${email}.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel integration-panel"><h2>Company onboarding</h2><p>Create an organization and its first employee. Send their invitation after reviewing the saved details.</p><form onSubmit={create} className="onboarding-form"><label>Company or organization name<input name="name" className="form-input" required minLength={2} maxLength={100}/></label><label>Individual name<input name="personName" className="form-input" required minLength={2} maxLength={100}/></label><label>Individual email<input name="email" className="form-input" type="email" required/></label><button className="primary-button" disabled={busy}>{busy?'Working…':'Create organization'}</button></form><hr className="onboarding-divider"/><label className="company-selector">Organization <select className="form-input" value={currentId} disabled={busy} onChange={e=>onSelect(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><h3>Employees</h3>{employees.filter(e=>e.active).map(e=><div key={e.id} className="onboarding-person"><div><strong>{e.name}</strong><span>{e.email}</span><small>{invitations.find(i=>i.email===e.email.toLowerCase())?.status==='sent'?'Invitation sent':'Employee · invitation available'}</small></div><button className="outline-button" disabled={busy} onClick={()=>void send(e.email,e.id)}><Mail size={16}/>Send invite</button></div>)}{!employees.some(e=>e.active)&&<p className="muted">No employees saved in this organization.</p>}{!!administrators.length&&<><h3>Company administrators</h3>{administrators.map(a=><div key={a.email} className="onboarding-person"><div><strong>{a.email}</strong><small>{a.status}</small></div><button className="outline-button" disabled={busy} onClick={()=>void send(a.email)}>Send invite</button></div>)}</>}{error&&<p className="feedback-error" role="alert">{error}</p>}{message&&<p className="feedback-success" role="status">{message}</p>}</section>;
}
