'use client';
import {useState,type FormEvent} from 'react';
import {Star,MessageSquare} from 'lucide-react';
import {platformFeedback} from '@/lib/platform-feedback';
import type {SupportModel} from './support-settings';
export default function PlatformFeedback({model}:{model:SupportModel}){
 const [rating,setRating]=useState(0),[busy,setBusy]=useState(false),[success,setSuccess]=useState(''),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setSuccess('');setError('');try{await model.send(platformFeedback(rating,String(new FormData(form).get('comment')??'')));form.reset();setRating(0);setSuccess('Thank you. Your rating and comments were saved for the platform owners. View replies under Contact and feedback.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel integration-panel platform-feedback"><div className="protection-title"><span className="protection-icon"><MessageSquare size={22}/></span><div><h2>Rate your experience</h2><p>Your feedback helps improve PhishAware.</p></div></div><form className="support-form" onSubmit={submit}><fieldset className="feedback-rating" disabled={busy}><legend>Your rating</legend><div>{[1,2,3,4,5].map(value=><label key={value} className={rating===value?'selected':''}><input type="radio" name="rating" value={value} checked={rating===value} onChange={()=>setRating(value)} required/><Star size={24} fill={value<=rating?'currentColor':'none'}/><span>{value}<span className="sr-only"> out of 5 stars</span></span></label>)}</div><p className="muted">1: Needs improvement · 5: Excellent</p></fieldset><label>Comments<textarea className="form-input" name="comment" rows={5} minLength={10} maxLength={3900} required disabled={busy} placeholder="What worked well? What should we improve?"/></label><p className="muted">Sent privately to the platform owners. Comments and ratings are not published. Leave out passwords and private email content.</p><button className="primary-button" disabled={busy}>{busy?'Sending…':'Send feedback'}</button></form>{success&&<p className="feedback-success" role="status">{success}</p>}{error&&<p className="feedback-error" role="alert">{error}</p>}</section>;
}
