'use client';
import Image from 'next/image';
import {ArrowRight,ShieldCheck,Mail,BookOpen,Flag,Check} from 'lucide-react';
export default function PublicHome({onSignIn}:{onSignIn:()=>void}){
 return <div className="public-home redesigned-home">
  <a className="skip-link" href="#main-content">Skip to content</a>
  <header className="home-nav"><a className="home-brand" href="#"><ShieldCheck size={27}/>PhishAware<span>.</span></a><nav aria-label="Main navigation"><a href="#protection">What we do</a><a href="#how-it-works">How it works</a><button className="primary-button" onClick={onSignIn}>Sign in <ArrowRight size={16}/></button></nav></header>
  <main id="main-content">
   <section className="home-hero"><div className="hero-copy"><p className="home-eyebrow">EMAIL PROTECTION &amp; SECURITY AWARENESS</p><h1>Recognise phishing.<br/><span>Respond with confidence.</span></h1><p className="hero-description">Review email warning signs, practise with workplace examples, and build safer habits across your organization.</p><div className="home-actions"><button className="primary-button" onClick={onSignIn}>Open your workspace <ArrowRight size={18}/></button><a className="home-secondary" href="#protection">Explore PhishAware</a></div><p className="home-access"><Check size={15}/>Secure access for invited employees and administrators</p></div><div className="hero-photo"><Image src="/images/design/phishing-hook.webp" alt="Phishing hook above a red email envelope on a laptop" width={1400} height={753} priority/><div className="photo-note"><ShieldCheck size={23}/><div><strong>Pause before you respond.</strong><span>Check the sender. Verify the request.</span></div></div></div></section>
   <div className="home-capability-strip" aria-label="Platform features"><span><Mail size={16}/>Email risk review</span><span><BookOpen size={16}/>Eight practical lessons</span><span><Flag size={16}/>Report suspicious messages</span></div>
   <section className="home-features" id="protection"><div className="home-section-title"><p className="home-eyebrow">YOUR WORKDAY. YOUR SECURITY.</p><h2>Clear guidance for the next decision.</h2><p>One workspace for email checks, employee training, and company follow-up.</p></div><div className="home-feature-grid"><article><div className="feature-visual"><Image src="/images/design/email-warning.webp" alt="Email envelope displaying a warning symbol" width={639} height={360}/></div><div className="feature-content"><span className="feature-label">01 · REVIEW</span><h3>Email protection</h3><p>Connect your Google mailbox with your permission. Review Low, Medium, and High risk findings with suggested actions.</p><a href="#how-it-works">How email review works <ArrowRight size={15}/></a></div></article><article><div className="feature-visual feature-visual-light"><Image src="/images/design/secure-workspace.webp" alt="Illustration of a protected email workspace" width={500} height={500}/></div><div className="feature-content"><span className="feature-label">02 · PRACTISE</span><h3>Learn by practising</h3><p>Complete eight lessons and short quizzes. Practise identifying unusual requests in your simulation inbox.</p><a href="#how-it-works">Your learning path <ArrowRight size={15}/></a></div></article><article><div className="feature-visual"><Image src="/images/design/phishing-key.webp" alt="Keyboard with a red phishing key" width={572} height={349}/></div><div className="feature-content"><span className="feature-label">03 · FOLLOW UP</span><h3>Report and respond</h3><p>Report suspicious findings to your company administrators. High risk summaries raise alerts for their attention.</p><a href="#how-it-works">From warning to action <ArrowRight size={15}/></a></div></article></div></section>
   <section className="home-workflow" id="how-it-works"><div className="workflow-photo"><Image src="/images/design/awareness-desk.webp" alt="Employee reviewing a phishing warning on a laptop" width={1400} height={934}/><span className="workflow-caption">Security awareness starts with a moment of review.</span></div><div><p className="home-eyebrow">GET STARTED IN YOUR COMPANY WORKSPACE</p><h2>Join. Review.<br/>Keep learning.</h2><ol><li><span>01</span><div><h3>Accept your invitation</h3><p>Open your administrator’s invitation and set your PhishAware password.</p></div></li><li><span>02</span><div><h3>Connect and review</h3><p>Connect your Google mailbox with your consent. Review findings in Email protection.</p></div></li><li><span>03</span><div><h3>Practise and complete</h3><p>Complete training, practise spotting warning signs, and share concerns with your company.</p></div></li></ol></div></section>
   <section className="home-trust"><ShieldCheck size={30}/><div><h2>Your mailbox, with your permission.</h2><p>Google access is read only. Message bodies and attachments are not stored. Administrators receive risk summaries and reports, rather than access to your inbox.</p><p className="home-limits">Risk ratings help you review warning signs. A Low risk rating does not guarantee an email is safe.</p></div></section>
   <section className="home-cta"><div><p className="home-eyebrow">YOUR NEXT STEP</p><h2>Bring awareness into your workday.</h2><p>Already invited? Sign in to your company workspace.</p></div><button className="primary-button" onClick={onSignIn}>Sign in to PhishAware <ArrowRight size={18}/></button></section>
  </main><footer className="home-footer"><a className="home-brand" href="#"><ShieldCheck size={22}/>PhishAware<span>.</span></a><p>Employee awareness. Practical email protection.</p></footer>
 </div>;
}
